// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4001.frc2016Explore.subsystems;

import org.usfirst.frc4001.frc2016Explore.RobotMap;
import org.usfirst.frc4001.frc2016Explore.commands.*;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.DigitalInput;

	
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Intake extends Subsystem {

    private final DigitalInput limitSwitch = RobotMap.intakelimitSwitch;
    private final CANTalon controller = RobotMap.intakecontroller;


    public void initDefaultCommand() {

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void receive(){
    	// roll in the ball
    	controller.set(0.5);
    }
    
    public void stop(){
    	// halt movement of intake
    	controller.set(0);
    }
    
    public void eject(){
    	// eject the ball at half speed
    	controller.set(-0.5);
    }
    
    public void fire(){
    	// eject the ball at full speed
    	controller.set(-1);
    }
    
    public boolean ballset(){
    	// ball is set in position
    	return !(limitSwitch.get());
    }
    
}

